ERROR_PARSER_NOT_INITIALIZED = -1
ERROR_PARSER_INPUT_FOLDER_NOT_FOUND = -4
ERROR_PARSER_INPUT_FOLDER_EMPTY = -5
ERROR_PARSER_KEY_NOT_FOUND = 4
ERROR_PARSER_KEY_VALUES_NOT_FOUND = 5
ERROR_PARSER_REG_HIVE_NOT_SUPPORTED = 100
ERROR_PARSER_REG_INCORRECT_INPUT_DATA = 104
ERROR_PARSER_ARGS_INCORRECT_DELIMITER_FORMAT = 110

# 300 - 400
ERROR_DECOMPRESSOR_DECOMPRESSION_SUCCESS = 300
ERROR_DECOMPRESSOR_SUPPORTED_ARCHIVE = 301
ERROR_DECOMPRESSOR_FORMAT_NOT_SUPPORTED = 302
ERROR_DECOMPRESSOR_ARCHIVE_NOT_FOUND = 304

PRINT_DISTINCT = True
PRINT_ALL = False